'use client';
import { LoadingSpinner } from '@/components/ui/LoadingSpinner';
import React, { useState, useEffect } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { apiClient } from '@/lib/api/client';

export default function ProfilePage() {
  const { id } = useParams<{ id: string }>();
  const router = useRouter();
  const [profile, setProfile] = useState<Record<string, string>>({});
  const [supp, setSupp] = useState<Record<string, string>>({});
  const [avatarUrl, setAvatarUrl] = useState('');
  const [uploading, setUploading] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    Promise.all([
      apiClient<any>(`/admin/skills/${id}/supplement`),
      apiClient<any>(`/admin/skills/${id}/audit-dashboard`)
    ]).then(([suppData, dashData]) => {
      setAvatarUrl(dashData?.skill?.avatarUrl || '');
      setSupp({
        displayName: suppData.displayName || dashData?.skill?.displayName || '',
        ownerName: suppData.ownerName || dashData?.skill?.ownerName || '',
        ownerTitle: suppData.ownerTitle || dashData?.skill?.ownerTitle || '',
        department: suppData.department || dashData?.skill?.department || '',
        seniority: suppData.seniority || dashData?.skill?.seniority || '',
        limitations: suppData.limitations || dashData?.skill?.limitations || '',
        publishNotes: suppData.publishNotes || dashData?.skill?.publishNotes || '',
        openingMessage: suppData.openingMessage || dashData?.skill?.openingMessage || '',
      });
      const p = dashData?.profile || {};
      setProfile({
        personality: p.personality || '',
        speakingStyle: p.speakingStyle || '',
        background: p.background || '',
        commonPhrases: p.commonPhrases || '',
        knowledgeDomains: p.knowledgeDomains || '[]',
        communicationPreferences: p.communicationPreferences || '[]',
        weaknessNotes: p.weaknessNotes || '',
      });
    }).catch(() => {}).finally(() => setLoading(false));
  }, [id]);

  const updateProfile = (k: string, v: string) => setProfile(p => ({ ...p, [k]: v }));
  const updateSupp = (k: string, v: string) => setSupp(p => ({ ...p, [k]: v }));

  const handleUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setUploading(true);
    try {
      const formData = new FormData();
      formData.append('file', file);
      const res = await apiClient<{ avatarUrl: string }>(`/admin/skills/${id}/avatar`, {
        method: 'POST', body: formData,
      });
      const url = (res as any)?.data?.avatarUrl || (res as any)?.avatarUrl || '';
      setAvatarUrl(url);
    } catch { alert('头像上传失败'); }
    setUploading(false);
  };

  const handleSave = async () => {
    setSaving(true);
    try {
      await Promise.all([
        apiClient(`/admin/skills/${id}/supplement`, { method: 'PUT', body: JSON.stringify(supp) }),
        apiClient(`/admin/skills/${id}/profile`, { method: 'PUT', body: JSON.stringify(profile) }),
      ]);
      setSaved(true); setTimeout(() => setSaved(false), 2000);
    } catch { alert('保存失败'); }
    setSaving(false);
  };

  if (loading) return <LoadingSpinner />;

  const isAutoGenerated = profile.personality && profile.personality.length > 0;

  return (
    <div className="max-w-3xl mx-auto p-6">
      <div className="flex items-center justify-between mb-6">
        <div>
          <button onClick={() => router.back()} className="text-sm text-muted-foreground hover:text-foreground mb-1">← 返回</button>
          <h1 className="text-xl font-bold">画像与发布信息</h1>
        </div>
        <button onClick={handleSave} disabled={saving}
          className={`px-6 py-2 rounded-lg text-sm text-white ${saved ? 'bg-green-500' : 'bg-primary hover:bg-primary-hover'} disabled:opacity-50`}>
          {saving ? '保存中...' : saved ? '✓ 已保存' : '保存全部'}
        </button>
      </div>

      {/* Section 1: AI 生成的画像 */}
      <div className="bg-surface-2 rounded-xl border border-border p-6 mb-6">
        <div className="flex items-center gap-2 mb-4">
          <h2 className="text-lg font-semibold">🧠 AI 分身画像</h2>
          {isAutoGenerated && <span className="text-xs bg-success-bg text-success px-2 py-0.5 rounded-full">AI 自动生成</span>}
        </div>
        <p className="text-sm text-muted-foreground-2 mb-4">从萃取结果中自动提炼，可手动修改。影响分身对话时的语气、思维方式和知识范围。</p>
        
        <Field label="性格" value={profile.personality} onChange={v => updateProfile('personality', v)} textarea placeholder="理性、沉稳，善于倾听后精准出击" />
        <Field label="说话风格" value={profile.speakingStyle} onChange={v => updateProfile('speakingStyle', v)} textarea placeholder="简洁有力，每句话落到客户痛点上" />
        <Field label="从业背景" value={profile.background} onChange={v => updateProfile('background', v)} textarea placeholder="10年金融科技销售，专注银行客户" />
        <Field label="口头禅" value={profile.commonPhrases} onChange={v => updateProfile('commonPhrases', v)} placeholder="让我先理解你的处境..." />
        <Field label="知识领域" value={profile.knowledgeDomains} onChange={v => updateProfile('knowledgeDomains', v)} placeholder='["金融","B2B","大客户"]' />
        <Field label="沟通偏好" value={profile.communicationPreferences} onChange={v => updateProfile('communicationPreferences', v)} placeholder='["先听后说","数据驱动"]' />
        <Field label="已知弱点" value={profile.weaknessNotes} onChange={v => updateProfile('weaknessNotes', v)} textarea placeholder="高压场景偶尔回避" />
      </div>

      {/* Section 2: 发布信息 */}
      <div className="bg-surface-2 rounded-xl border border-border p-6">
        <h2 className="text-lg font-semibold mb-4">📋 发布信息</h2>
        <p className="text-sm text-muted-foreground-2 mb-4">销冠本人的基本信息，用于审核和对外展示。</p>

        {/* 头像上传 */}
        <div className="flex items-center gap-5 mb-6 p-4 bg-surface rounded-xl border border-border">
          <div className="w-20 h-20 rounded-full overflow-hidden bg-gradient-to-br from-blue-100 to-blue-50 ring-2 ring-blue-100/50 flex items-center justify-center flex-shrink-0">
            {avatarUrl ? (
              <img src={avatarUrl} alt="头像" className="w-full h-full object-cover" />
            ) : (
              <span className="text-2xl text-[#2563EB] font-bold">{supp.ownerName?.[0] || '?'}</span>
            )}
          </div>
          <div>
            <p className="text-sm font-medium text-foreground mb-1">分身头像</p>
            <p className="text-xs text-muted-foreground-2 mb-2">上传销冠本人照片，用于问答和聊天模式中的 AI 分身头像</p>
            <label className={`inline-block px-4 py-1.5 text-xs rounded-lg cursor-pointer transition-colors ${uploading ? 'bg-muted text-muted-foreground' : 'bg-primary text-white hover:bg-primary-hover'}`}>
              {uploading ? '上传中...' : avatarUrl ? '更换头像' : '上传头像'}
              <input type="file" accept="image/*" className="hidden" onChange={handleUpload} disabled={uploading} />
            </label>
            {avatarUrl && (
              <button onClick={() => setAvatarUrl('')} className="ml-2 text-xs text-muted-foreground hover:text-danger">移除</button>
            )}
          </div>
        </div>

        <div className="grid grid-cols-2 gap-4">
          <Field label="展示名称" value={supp.displayName} onChange={v => updateSupp('displayName', v)} placeholder="潘露婷" />
          <Field label="真实姓名" value={supp.ownerName} onChange={v => updateSupp('ownerName', v)} placeholder="潘露婷" />
          <Field label="职位" value={supp.ownerTitle} onChange={v => updateSupp('ownerTitle', v)} placeholder="招商专员" />
          <Field label="部门" value={supp.department} onChange={v => updateSupp('department', v)} placeholder="台商项目" />
          <Field label="从业年限" value={supp.seniority} onChange={v => updateSupp('seniority', v)} placeholder="3年" />
        </div>
        <div className="mt-4">
          <Field label="局限性说明" value={supp.limitations} onChange={v => updateSupp('limitations', v)} textarea placeholder="分身可能在某些场景下回答不够准确..." />
          <Field label="开场白（一句话自我介绍）" value={supp.openingMessage} onChange={v => updateSupp('openingMessage', v)} textarea placeholder="我用10年B2B销售经验，帮你拿下每一个关键客户" />
          <Field label="审核备注" value={supp.publishNotes} onChange={v => updateSupp('publishNotes', v)} textarea placeholder="管理员审核备注..." />
        </div>
      </div>
    </div>
  );
}

function Field({ label, value, onChange, placeholder, textarea }: {
  label: string; value: string; onChange: (v: string) => void;
  placeholder: string; textarea?: boolean;
}) {
  return (
    <div className="mb-3">
      <label className="block text-xs font-medium text-muted-foreground mb-1">{label}</label>
      {textarea
        ? <textarea value={value || ''} onChange={e => onChange(e.target.value)} placeholder={placeholder}
            className="w-full border border-border rounded-lg p-2.5 text-sm h-20 resize-y focus:border-primary focus:outline-none" />
        : <input value={value || ''} onChange={e => onChange(e.target.value)} placeholder={placeholder}
            className="w-full border border-border rounded-lg p-2 text-sm focus:border-primary focus:outline-none" />}
    </div>
  );
}
